---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebserver-deployment
  labels:
    app: mywebserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebserver
  template:
    metadata:
      labels:
        app: mywebserver
    spec:
      containers:
      - name: mywebserver
        image: ruliezz/kubernetesworkshop:latest
        ports:
        - containerPort: 8088
---       
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mywebserver
  name: mywebserver-deployment
spec:
  ports:
  - nodePort: 30088
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: mywebserver
  type: NodePort
